[package]
name        = "flix-parsers"
description = "A simple parser library for Flix using higher-order functions as parsers"
version     = "0.1.10"
flix         = "0.56.0"
license     = "Apache-2.0"
authors     = ["Jakob Schneider"]
